/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/renderer/index.html",
    "./src/renderer/src/**/*.{js,ts,jsx,tsx,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'on-surface': '#111c2d',
        'on-surface-variant': '#40484b',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'outline': '#70787c',
        'outline-variant': '#c0c8cb',
        'surface-tint': '#306576',
        'primary': '#003441',
        'on-primary': '#ffffff',
        'primary-container': '#0f4c5c',
        'on-primary-container': '#87bbce',
        'inverse-primary': '#9acee1',
        'secondary': '#006b5f',
        'on-secondary': '#ffffff',
        'secondary-container': '#6df5e1',
        'on-secondary-container': '#006f64',
        'tertiary': '#452900',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#643d00',
        'on-tertiary-container': '#f8a110',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#b6ebfe',
        'primary-fixed-dim': '#9acee1',
        'on-primary-fixed': '#001f28',
        'on-primary-fixed-variant': '#114d5d',
        'secondary-fixed': '#71f8e4',
        'secondary-fixed-dim': '#4fdbc8',
        'on-secondary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#005048',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        'background': '#f9f9ff',
        'on-background': '#111c2d',
        'surface-variant': '#d8e3fb',
      },
      fontFamily: {
        'public-sans': ['"Public Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      spacing: {
        'base': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'gutter': '20px',
        'margin': '32px',
      },
    },
  },
  plugins: [],
}

